
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module mcu(

	//////////// CLOCK //////////
	input CLK,

	//////////// 7-segment decoder //////////
	output [6:0] HEX0,
	output [6:0] HEX1,
	output [6:0] HEX2,
	output [6:0] HEX3,
	
	//////////// LED /////////////
	output [9:0] LED,
	
	//////////// SWITCH //////////
	input [9:0] SW,
	
	//////////// BUTTON //////////
	input [2:0] BTN
	
);
//*******************************//
// add module here
wire[7:0] out;
cpu cpu1(.reset(!BTN[0]),.clk(CLK),.port_b_out(out));
assign LED[7:0] = out;
seven_seg_decoder seg1(.data_in(out[3:0]),.hex_out(HEX1));
endmodule